### ISSUE TITLE
Implementation TODO

### ISSUE THREAD

**Issue by jgeboski** [jgeboski/bitlbee-facebook#1]
Pretty much everything has been implemented as of 53cedfa.  Please open new issues.

**Comment by toogy** [comment]
1. Being able to leave a groupchat with a `/leave` command could be interesting!
Since `/leave` is already used by IRC clients, we should find a better name. `/bye`? `flee`?

2. Being able to appear offline to your contacts (who use the real facebook chat) could be interesting too. I don't like people seeing me online all the time (even though bitlbee is always connected). We could use the `/away` command (already used by bitlbee).

**Comment by Zopieux** [comment]
I do agree `/away` would be a very useful feature.

**Comment by seirl** [comment]
Autojoin a channel when you receive a message in a channel you're not in.

**Comment by jgeboski** [comment]
List updated!

> Being able to leave a groupchat with a `/leave` command could be interesting!

The plugin certainly needs a way to leave a group chat.  That said, bitlbee will not handle such a command as is.  Patches would need to be sent upstream, which may or may not be viable.

**Comment by toogy** [comment]
Like most of us, my IRC client runs in a terminal. I like to browse the links with some shortcut (provided by my terminal which is termite -- it's on GitHub).

Thing is, when someone sends a picture (in a group or simple chat), `* Non-Displayable Attachments *` is printed (as a normal message). It would be nice to have the link of the picture displayed (direct link) so that we don't have to go back to facebook.com to see the picture that was sent.

**Comment by jgeboski** [comment]
On the list already.

**Comment by toogy** [comment]
Sorry, I should learn to read. :/

**Comment by toogy** [comment]
Any idea about how to implement this `/away` feature?

**Comment by andreimarcu** [comment]
Thanks for the awesome bitlbee plugin! I'm especially excited about it since they're shutting down xmpp soon.

I wanted to suggest maybe also handling messages not from your friends. They show up as _12xxxxxx and not the names. They also show up in the bitlbee control channel instead of separate queries.

**Comment by jgeboski** [comment]
@andreimarcu I'll look into it.  This is more of a bitlbee issue, though.

**Comment by dequis** [comment]
@andreimarcu You could do `set handle_unknown add_private` to get them in a query.

**Comment by andreimarcu** [comment]
That's very helpful. Thanks @dequis.

Anything that I could do about the names?

**Comment by jgeboski** [comment]
@andreimarcu That is due to the plugin not calling `imcb_buddy_nick_hint()` for the handle.  I'll look into addressing this.

**Comment by andreimarcu** [comment]
Thank you @jgeboski !

I would like to mention that for the "Display links to attachments" improvement, maybe we should consider the :+1: action as an attachement or something different, since when someone sends a :+1: there is nothing displayed on bitlbee's side (normal attachments display a "non-displayable attachment", this doesn't display anything).

**Comment by jgeboski** [comment]
Yeah, displaying the media or links to the media is a top priority when I get some free time. :)

**Comment by jgeboski** [comment]
@andreimarcu as per the previous issue with nicknames, is this related to #22, or is it just someone of whom you have not added?

**Comment by andreimarcu** [comment]
These were people that aren't added.

**Comment by jgeboski** [comment]
Yeah, I'll have to look into doing this.  I forget all the relative things related to assigning information to users who are not actual buddies within bitlbee.

**Comment by ycny** [comment]
How about automatic join to the private chat after login, if there are unread messages? Or just to be able to see unread messages as a chat history? 
Right now, I still need to check all messages on the phone if I wasn't using bitlbee in a certain period of time.

**Comment by ticoombs** [comment]
+1 for unread messages. This is a big annoyance/gripe for me.

**Comment by maxux** [comment]
A way to receive our own message sent from somewhere else ? It's feasable with Message Tags (http://ircv3.net/specs/core/message-tags-3.2.html).

(for irssi users, here is a patch to handle it: http://bugs.irssi.org/index.php?do=details&task_id=833, it's used too by znc privmsg plugin)

**Comment by michalrus** [comment]
@maxux, it should work without message tags, why not? E.g. InspIRCd uses `:my_nick!u@h PRIVMSG #chan :msg` to show channel history. Irssi renders my historical messages just fine when I’m in this history, too.

**Comment by dequis** [comment]
>A way to receive our own message sent from somewhere else ? It's feasable with Message Tags (http://ircv3.net/specs/core/message-tags-3.2.html).

Did you even read the spec?

>(for irssi users, here is a patch to handle it: http://bugs.irssi.org/index.php?do=details&task_id=833, it's used too by znc privmsg plugin)

Did you even read the ticket description?

Heh, sorry, I had to. Mentioning message-tags was just... random. Anyway self-message support is irrelevant to bitlbee-facebook, needs to be implemented in bitlbee instead, since it's an irc protocol implementation detail. I've been working on related stuff for a while. Soon™

Also, regarding that irssi patch, it's already applied in git versions of irssi. Most other clients don't need that and work out of the box.

**Comment by maxux** [comment]
@michalrus: for channels, yes, but it won't works for queries, because you can't receive message from yourself and put it on the right query windows without Message Tags.

@dequis: just keep the "own message from somewhere else" idea from my message :)
