### ISSUE TITLE
Stuck at « Requesting authentication token »

### ISSUE THREAD

**Issue by maxux** [jgeboski/bitlbee-facebook#23]
I just reinstalled the plugin today because the jabber seems down for me. It was working about one month ago. I made a fresh install, add my account, and I cannot go further that:
````
19:57:19 <@root> facebook - Logging in: Connecting
19:57:19 <@root> facebook - Logging in: Requesting authentication token
19:59:19 <@root> facebook - Login error: Connection timeout
19:59:19 <@root> facebook - Logging in: Signing off..
19:59:19 <@root> facebook - Login error: Request closed
````

A friend has exactly the same problem as me, any idea ?

**Comment by dequis** [comment]
Works for me. Could be some firewall issue. Try doing `curl -v https://b-api.facebook.com/` in the same server that bitlbee is running at.

If that's not the problem, join #bitlbee in irc.oftc.net for faster support.

**Comment by dequis** [comment]
Okay, solved, turned out to be the hosting provider sucking at ipv6.

The "solution" was to manually lookup `api.facebook.com`, `b-api.facebook.com`, `graph.facebook.com` and `mqtt.facebook.com` and add their ipv4 addresses to /etc/hosts (Disabling ipv6 globally would have worked too, but apparently it's needed in that server)

@maxux close!

**Comment by maxux** [comment]
With @dequis's help on IRC, seems to be a ipv6 with ovh issue.

Fixed by setting on `/etc/hosts`:
````
173.252.110.29  b-api.facebook.com
173.252.110.27  api.facebook.com
173.252.110.27  graph.facebook.com
173.252.102.16  mqtt.facebook.com
````

Or disable ipv6: `echo 1 > /proc/sys/net/ipv6/conf/eth0/disable_ipv6`

Thanks
