### ISSUE TITLE
Numbered release

### ISSUE THREAD

**Issue by thypon** [jgeboski/bitlbee-facebook#46]
Having a numbered release could help packaging this one for many distros. What's needed to complete this step?

**Comment by jgeboski** [comment]
Nothing. I have just been waiting since 53cedfa to make sure things were stable. I plan to tag `1.0.0` in the near future.

**Comment by niklaas** [comment]
Once that is done (and it is not planned to include `bitlbee-facebook` into bitlbee) I'd provide a port for FreeBSD.

**Comment by TheDreamer** [comment]
What's the ETA for the FreeBSD port now that the old way is completely defunct?

**Comment by niklaas** [comment]
What do you mean with "the old way is completely defunct"?

The port will be done quite fast since the installation is actually quite straightforward. But at the moment I am occupied with other projects and as far as I know there's still no version number?

**Comment by jgeboski** [comment]
> But at the moment I am occupied with other projects and as far as I know there's still no version number?

Correct. Hopefully soon, though (twoish weeks?).

**Comment by niklaas** [comment]
I should have some time then too. @TheDreamer remember that it needs some time until a port actually finds its way to the port tree, this can take months. I will provide a github repository with the port though, so you should be able to plug it into your ports tree on your own.

**Comment by TheDreamer** [comment]
Well, it was Dec 10th, that I noticed that facebook using password login was completely not working anymore.  And, since the provision of a FreeBSD port was mentioned, I was hoping it might happen sooner than later now.

Though now that I should have some free time, I guess I can look at doing the port if necessary....  either that or catch up on my backlog of patches to FreeBSD ports (perhaps after I rip out all references to other site I now no longer manage from my CFEngine server, along with other rituals with virtual fire.)

**Comment by jgeboski** [comment]
I will be tagging within the next day or two. I am waiting on one possible issue.

**Comment by thypon** [comment]
:+1:

**Comment by jgeboski** [comment]
At long last, we now have a [release](https://github.com/jgeboski/bitlbee-facebook/releases/tag/v1.0.0).
