### ISSUE TITLE
Messages are not sent

### ISSUE THREAD

**Issue by maxux** [jgeboski/bitlbee-facebook#9]
Within 3 hours, with about 200 lines sent from bitlbee-facebook, there are about 15-20 not sent correctly (and sometime I don't get some messages too). I don't know how nor why, there are no error/disconnection on status the console.

**Comment by MTecknology** [comment]
Do these happen to have quotes?
I was about to report an issue as well. If I try to send anything wrapped in quotes, the message will not make it through. ```foo "bar buz"```

**Comment by maxux** [comment]
I just tried, I can confirm that message with quotes are not sent. I'll try to see if it's limited quotes.

**Comment by Zopieux** [comment]
This is *not* limited to quotes.

These messages were sent successfully:
>`coucou`
>`de rien`

Just a few seconds after, this one (and all the following) were *not* sent:
>`sachant que mon avion décollait à 15h30 je sais pas où il a trouvé ça, bref`

Maybe non-ASCII characters are also an issue. I'll try to do more tests with friends and come back with the results here.

**Comment by Zopieux** [comment]
Results so far: double quotes are *always* killing the communication. Non-ASCII characters are actually perfectly fine, it seems it's related to a specific flow of messages rather than individual messages. For what we've observed, there is some kind of queuing/rate limiting be I'm not sure if it's bitlbee-facebook or Facebook. I'll add/enable some debug so I can further investigate. Some messages were delayed for as long as 3 minutes !

**Comment by jgeboski** [comment]
This issue will require more investigation.  I would assume there is some sort of limit.

**Comment by dequis** [comment]
Submitted PR #12 to deal with the double quotes issue

**Comment by jgeboski** [comment]
This should be resolved as of 059b686.
